name: "CI"

on: [push]

jobs:
  ruff-check:
    name: ruff-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/ruff-action@v4.1.0
        with:
          args: "check"

  pytest:
    name: pytest
    needs: [ruff-check]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.12", "3.13", "3.14"]
        solver: ["libmamba", "rattler"]
    steps:
      - uses: actions/checkout@v7
      - uses: conda-incubator/setup-miniconda@v4
        with:
          auto-update-conda: true
          conda-solver: ${{ matrix.solver }}
          environment-file: environment.yml
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
      - run: pip install --no-deps -e .
      - run: pytest .
      - uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
